title: IEEE at Cornell Wiki
description: Class information for IEEE-related courses and activities at Cornell University

header_pages:
- index.md
- about.md
- contributing.md

url: "https://ieeeatcornell.github.io"
baseurl: "/wiki"

style: light
markdown: kramdown
mathjax: true

footer: 'follow us on <a href="https://www.instagram.com/ieee.at.cornell/">instagram</a>'

theme: just-the-docs
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-remote-theme
permalink: /:categories/:title/

callouts:
  warning:
    title: Warning
    color: red

favicon_ico: "/assets/bolt.png"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/IEEEAtCornell/wiki"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

collections:
  courses:
    output: true
