title: IEEE at Cornell Wiki
description: Class information for IEEE-related courses and activities at Cornell University

header_pages:
- index.md
- about.md
- contributing.md

url: "https://ieeeatcornell.github.io"
baseurl: "/wiki"

style: light
markdown: kramdown
mathjax: true

footer: 'follow us on <a href="https://www.instagram.com/ieee.at.cornell/">instagram</a>'

theme: just-the-docs
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-remote-theme
permalink: /:categories/:title/

callouts:
  warning:
    title: Warning
    color: red

favicon_ico: "/assets/bolt.png"
remote_theme: just-the-docs/just-the-docs
